#!/bin/bash

COMMAND=$1

# shellcheck source=config
. config
. language_support.sh
. repl_modules

repl_has() {
  type "${1-}" > /dev/null 2>&1
}

#######################################
# Update a line in the config file.
# Globals:
#   None
# Arguments:
#   $1 - Variable to update (e.g., "LAST_RUN=") [MUST include equals sign, no leading/trailing spaces]
#   $2 - Value to update variable with (e.g., "cpp" for LAST_RUN=) [no leading/trailing spaces]
# Returns:
#   None
#######################################
repl_update_config() {
  local SCRIPTPATH
  SCRIPTPATH="$( cd "$(dirname "$0")" || exit ; pwd -P )"

  sed -i "s@^\($1\).*@\1\"$2\"@" "${SCRIPTPATH}/config"
}

repl_edit() {
  for lang in "${LANGUAGES[@]}"; do
    if [ "$EXT" = "$lang" ]; then
      local env="$lang"
      break
    fi
  done

  if [ -z "$env" ]; then
    echo "repl: Filetype '.${EXT}' not supported"
    exit 1
  fi

  echo "Creating ${env} repl..."

  local filepath="/tmp/repl.${EXT}"

  # Call the appropriate module from `repl_modules`
  "repl_$env" edit "$filepath"

  repl_update_config "LAST_RUN=" "$EXT"

  if repl_has "$EDITOR"; then
    eval "$EDITOR $filepath"
  else
    echo "repl: editor '$EDITOR' does not exist. Check config file."
    echo "      Example:"
    echo "          EDITOR=\"vim\""
    echo "      or"
    echo "          EDITOR=\"/usr/bin/vim\""
    exit 1
  fi
}

repl_status() {
  if [ -n "$LAST_RUN" ] && [ -e "/tmp/repl.${LAST_RUN}" ]; then
    echo "repl: status: currently in a $LAST_RUN repl"
  else
    echo "repl: No current repl"
  fi
}

repl_run() {
  for lang in "${LANGUAGES[@]}"; do
    if [ "$lang" = "$LAST_RUN" ]; then
      # Call the appropriate module from `repl_modules`
      "repl_$lang" "run" && \
      return 0
    fi
  done

  echo "repl: could not detect existing repl"
  echo "      create a repl first (e.g., 'repl js')"
  exit 1
}

main() {
  case "$COMMAND" in
  "")
    echo "repl: missing operand"
    echo "      Try 'repl js'"
    exit 1
    ;;
  run)
    repl_run
    ;;
  status)
    repl_status
    ;;
  *)
    EXT="$COMMAND"
    repl_edit
    ;;
  esac
}

main

exit 0
